# ä¾¦å¬åœ°å€, ipv6 ä½¿ç”¨ [::]:9394
grpc_addr = "0.0.0.0:9394"
http_addr = "0.0.0.0:8080"
# é»˜è®¤30sæ— ä¸ŠæŠ¥åˆ¤å®šä¸‹çº¿
offline_threshold = 30

# ç®¡ç†å‘˜è´¦å·,ä¸è®¾ç½®é»˜è®¤éšæœºç”Ÿæˆï¼Œç”¨äºæŸ¥çœ‹ /detail, /map
admin_user = ""
admin_pass = ""

# hosts è·Ÿ hosts_group ä¸¤ç§é…ç½®æ¨¡å¼ä»»æŒ‘ä¸€ç§é…ç½®å³å¯
# name ä¸»æœºå”¯ä¸€æ ‡è¯†ï¼Œä¸å¯é‡å¤ï¼Œalias ä¸ºå±•ç¤ºå
# ä½¿ç”¨ ansible æ‰¹é‡éƒ¨ç½²æ—¶å¯ä»¥ç”¨ä¸»æœº hostname ä½œä¸º nameï¼Œç»Ÿä¸€å¯†ç 
# notify = false å•ç‹¬ç¦æ­¢å•å°æœºå™¨çš„å‘Šè­¦ï¼Œä¸€èˆ¬é’ˆå¯¹ç½‘ç»œå·®ï¼Œé¢‘ç¹ä¸Šä¸‹çº¿
# monthstart = 1 æ²¡å¯ç”¨vnstatæ—¶ï¼Œè¡¨ç¤ºæœˆæµé‡ä»æ¯æœˆå“ªå¤©å¼€å§‹ç»Ÿè®¡
# disabled = true å•æœºç¦ç”¨ï¼Œè·Ÿåˆ é™¤è¿™æ¡é…ç½®çš„æ•ˆæœä¸€æ ·
hosts = [
  {name = "h1", password = "p1", alias = "n1", location = "ğŸ ", type = "kvm"},
  {name = "h2", password = "p2", alias = "n2", location = "ğŸ¢", type = "kvm", disabled = false},
]

#hosts = [
#  {name = "h1", password = "p1", alias = "n1", location = "ğŸ ", type = "kvm"},
#  {name = "h2", password = "p2", alias = "n2", location = "ğŸ¢", type = "kvm", disabled = false},
#  {name = "h3", password = "p3", alias = "n3", location = "ğŸ¡", type = "kvm", monthstart = 1},
#  {name = "h4", password = "p4", alias = "n4", location = "ğŸ¡", type = "kvm", notify = true},
#]

# !!! ä¸€é”®éƒ¨ç½²å¦‚æœæ²¡é—®é¢˜åˆ™ä¸éœ€è¦åŠ¨ï¼ŒServer ä¼šè‡ªè¡Œæ ¹æ®ä½ çš„åŸŸåç”Ÿæˆ server_url
# ä¿®æ­£ä¸€é”®éƒ¨ç½²ï¼Œè¯·è‡ªè¡Œæ›¿æ¢ ssr.rs ä¸ºä½ çš„åŸŸå,
# server_url = "https://ssr.rs/report"
# stat_client é»˜è®¤å®‰è£…çš„è·¯å¾„
workspace = "/opt/ServerStatus"
