# ä¾¦å¬åœ°å€, ipv6 ä½¿ç”¨ [::]:9394
grpc_addr = "0.0.0.0:9879"
http_addr = "0.0.0.0:9878"

# disabled = true å•æœºç¦ç”¨ï¼Œè·Ÿåˆ é™¤è¿™æ¡é…ç½®çš„æ•ˆæœä¸€æ ·
hosts = [
    { name = "h1", password = "p1", location = "ğŸ " },
    { name = "h2", password = "p2", location = "ğŸ¢" },
]

# server_url = "https://127.0.0.1:/report"
# stat_client é»˜è®¤å®‰è£…çš„è·¯å¾„
workspace = "/opt/server-status"
