# ä¾¦å¬åœ°å€, ipv6 ä½¿ç”¨ [::]:9394
grpc_addr = "0.0.0.0:9394"
http_addr = "0.0.0.0:8080"

# ç®¡ç†å‘˜è´¦å·,ä¸è®¾ç½®é»˜è®¤éšæœºç”Ÿæˆï¼Œç”¨äºæŸ¥çœ‹ /detail, /map
admin_user = ""
admin_pass = ""


# disabled = true å•æœºç¦ç”¨ï¼Œè·Ÿåˆ é™¤è¿™æ¡é…ç½®çš„æ•ˆæœä¸€æ ·
hosts = [
  {name = "h1", password = "p1", location = "ğŸ ", disabled = false},
  {name = "h2", password = "p2", location = "ğŸ¢", disabled = false},
]

# !!! ä¸€é”®éƒ¨ç½²å¦‚æœæ²¡é—®é¢˜åˆ™ä¸éœ€è¦åŠ¨ï¼ŒServer ä¼šè‡ªè¡Œæ ¹æ®ä½ çš„åŸŸåç”Ÿæˆ server_url
# ä¿®æ­£ä¸€é”®éƒ¨ç½²ï¼Œè¯·è‡ªè¡Œæ›¿æ¢ ssr.rs ä¸ºä½ çš„åŸŸå,
# server_url = "https://ssr.rs/report"
# stat_client é»˜è®¤å®‰è£…çš„è·¯å¾„
workspace = "/opt/ServerStatus"
